# 配置RabbitMQ的基本信息  ip 端口 username  password..
spring:
  rabbitmq:
    host: 122.9.140.213 # ip
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 这个参数默认是false，开启之后，则可以开启发布者回调函数
    publisher-confirms: true